name: 'Terraform'

on: 
  workflow_dispatch:
    inputs:
      bucketName:
        description: 'Nome do bucket S3 na AWS'     
        required: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Provides AWS credentials to Terraform
    # By default, Terraform checks the home directory for a .aws folder with a credential file
    # Documentation: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/create-shared-credentials-file.html
    - name: "Setup - Build AWS Credentials"
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

    # The triggered workflow receives the inputs
    - name: "Inputs - Bucket Name "
      run: |
        echo "Bucket Name: ${{ github.event.inputs.bucketName }}"

    # Downloads a specific version of Terraform CLI and adds it to PATH
    # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 1.1.4

    # Init pulls credentials from the .aws/credentials file by default
    - name: "Run - Terraform Init"
      run: terraform init -input=false

    # The id value is used for reference in the comment step via "steps.plan.outputs.stdout"
    # Note: Color is disabled to prevent messy characters from appearing in the pull request comment
    - name: "Run - Terraform Plan"
      id: plan
      run: terraform plan -var="bucket_name=${{ github.event.inputs.bucketName }}" -input=false -no-color
